const jobTitles = {
  Engineering: [
    "Civil engineer",
    "Mechanical engineer",
    "Chemical engineer",
    "Biological engineer",
    "Nuclear engineer",
    "Aerospace engineer",
    "Electrical engineer",
    "Environmental engineer",
    "Geological engineer",
    "Marine engineer",
    "Petroleum engineer",
    "Safety engineer",
    "Product engineer",
    "Compliance engineer",
    "Senior process engineer",
  ],

  Business: [
    "Project manager",
    "Sales manager",
    "Actuary",
    "Business teacher",
    "Business reporter",
    "Admissions representative",
    "Office manager",
    "Office clerk",
    "Assistant buyer",
    "Business development manager",
  ],

  //   Agriculture: [
  //     "Foresters",
  //     "Biochemist",
  //     "Food scientist",
  //     "Animal geneticist",
  //     "Farmer",
  //     "Wildlife biologist",
  //     "Horticulturist",
  //     "Plant nursery attendant",
  //     "Agriculture teacher",
  //     "Plant biologist",
  //     "Wildlife inspector",
  //     "Soil and plant scientist",
  //     "Beekeeper",
  //     "Aquatic ecologist",
  //     "Conservationist",
  //   ],

  //   Animal_Science: [
  //     "Veterinarian",
  //     "Zoologist",
  //     "Groomer",
  //     "Animal control officer",
  //     "Kennel attendant",
  //     "Pet walker",
  //     "Animal sitter",
  //     "Animal shelter manager",
  //     "Veterinary assistant",
  //     "Animal nutritionist",
  //     "Biologist",
  //     "Wildlife rehabilitator",
  //     "Breeder",
  //     "Veterinary pathologist",
  //     "Veterinary ophthalmologist",
  //   ],

  //   Cosmetology: [
  //     "Salon manager",
  //     "Makeup artist",
  //     "Nail technician",
  //     "Message therapist",
  //     "Barber",
  //     "Beautician",
  //     "Skin care specialist",
  //     "Fashion designer",
  //     "Esthetician",
  //     "Electrologist",
  //     "Cosmetology instructor",
  //     "Hairdresser",
  //     "Fashion show stylist",
  //     "Spa manager",
  //     "Wedding stylist",
  //   ],

  //   Customer_service: [
  //     "Call center agent",
  //     "Client services coordinator",
  //     "Technical support representative",
  //     "Virtual assistant",
  //     "Customer care associate",
  //     "Retail sales associate",
  //     "Cashier",
  //     "Concierge",
  //     "Customer service manager",
  //     "Help desk assistant",
  //     "Account coordinator",
  //     "Service advisor",
  //     "Bank teller",
  //     "Front desk coordinator",
  //     "Client services manager",
  //   ],

  //   Creative: [
  //     "Art director",
  //     "Graphic designer",
  //     "Writer",
  //     "Editor",
  //     "Illustrator",
  //     "Public relations specialist",
  //     "Actor",
  //     "Singer",
  //     "Producer",
  //     "Web developer",
  //     "Architect",
  //     "Multimedia animator",
  //     "Painter",
  //     "Tattoo artist",
  //     "Dancer",
  //     "Floral designer",
  //   ],

  //   Education: [
  //     "English teacher",
  //     "College professor",
  //     "Tutor",
  //     "Test scorer",
  //     "Test administrator",
  //     "Assistant professor",
  //     "Principal",
  //     "Superintendent",
  //     "Vice principal",
  //     "Substitute teacher",
  //     "Librarian",
  //     "Math teacher",
  //     "Science teacher",
  //     "Instructional designer",
  //     "Guidance counselor",
  //   ],

  //   Finance: [
  //     "Financial planner",
  //     "Financial advisor",
  //     "Budget analyst",
  //     "Credit analyst",
  //     "Financial services representative",
  //     "Financial manager",
  //     "Cost estimator",
  //     "Loan officer",
  //     "Investment banking analyst",
  //     "Financial auditor",
  //   ],

  //   Healthcare: [
  //     "Nurse",
  //     "Doctor",
  //     "Caregiver",
  //     "Physical therapist",
  //     "Personal trainer",
  //     "Pharmacist",
  //     "Pharmacy assistant",
  //     "Dental hygienist",
  //     "Orthodontist",
  //     "Travel nurse",
  //     "Dental assistant",
  //     "Occupational therapy aide",
  //     "Dentist",
  //     "Surgical technologist",
  //     "Dietitian",
  //   ],

  //   Hospitality: [
  //     "Travel agent",
  //     "Housekeeper",
  //     "Porter",
  //     "Casino host",
  //     "Hotel clerk",
  //     "Meeting planner",
  //     "Executive chef",
  //     "Tour guide",
  //     "Flight attendant",
  //     "Event manager",
  //   ],

  //   Human_resources: [
  //     "Human resources manager",
  //     "Compensations and benefits manager",
  //     "Administrative assistant",
  //     "Human resources generalist",
  //     "Talent acquisition coordinator",
  //     "Executive recruiter",
  //     "Human resources specialist",
  //     "Human resources director",
  //     "Human resources assistant",
  //     "Labor relations specialist",
  //     "Human resources consultant",
  //     "International human resources associate",
  //     "Human resources systems administrator",
  //     "Compensation advisor",
  //     "Training and development manager",
  //   ],

  //   Information_technology: [
  //     "UX designer",
  //     "UI developer",
  //     "IT manager",
  //     "Computer programmer",
  //     "SQL developer",
  //     "Software developer",
  //     "Web administrator",
  //     "Data architect",
  //     "Business intelligence developer",
  //     "Mobile application developer",
  //     "Information security analyst",
  //     "Front-end web developer",
  //     "Java developer",
  //     "Database manager",
  //     "Software engineer",
  //   ],

  //   Leadership: [
  //     "Chief of operations",
  //     "Team leader",
  //     "Manager",
  //     "Executive",
  //     "Director",
  //     "Supervisor",
  //     "Principal",
  //     "President",
  //     "Vice President",
  //     "Team lead",
  //   ],

  //   Operations: [
  //     "Chief operations officer",
  //     "Logistics coordinator",
  //     "Warehouse supervisor",
  //     "Supply chain specialist",
  //     "Distribution supervisor",
  //     "Supply chain coordinator",
  //     "Operations assistant",
  //     "Scrum master",
  //     "Continuous improvement lead",
  //     "Operations manager",
  //   ],

  //   Marketing: [
  //     "Marketing coordinator",
  //     "Marketing manager",
  //     "Marketing assistant",
  //     "Marketing director",
  //     "Product marketing manager",
  //     "Creative director",
  //     "Demand generation director",
  //     "Social media manager",
  //     "Account manager",
  //     "Brand manager",
  //     "Content marketing manager",
  //     "Marketing analyst",
  //     "Marketing consultant",
  //     "Social media coordinator",
  //     "Search engine optimization specialist",
  //   ],

  //   Sales: [
  //     "Sales representative",
  //     "Sales director",
  //     "Sales manager",
  //     "Insurance sales agent",
  //     "Telemarketer",
  //     "Retail salesperson",
  //     "Store manager",
  //     "Account executive",
  //     "B2B sales specialist",
  //     "Sales analyst",
  //     "Real estate broker",
  //     "Sales associate",
  //     "Sales consultant",
  //     "Collection agent",
  //     "Regional sales manager",
  //   ],
};

export default jobTitles;
